import requests
import json
headers = {
    'AccountKey': 'dGLJfclWR4amd1r8B29LKQ==',# Account Key generated by DataMall
    'accept': 'application/json'
}

def fetch_all(url):
    results = [] #Stores all file write requests into array tables 
    while True:
        new_results = requests.get(
            url,
            headers=headers,
            params={'$skip': len(results)}
        ).json()['value']
        #Recursively adds datapoints into the table 
        if new_results == []: 
            break
        else:
            results += new_results
    return results


#Current file dumps include :
                             #Bus Stop list
                             #Bus Service list
                             #Bus Routes list
#To be added,
                             #MRT Station list
                             #MRT Route list


if name == "pull":
    #Datapoints stored and dumped into .json files as stops.json
    Busstops = fetch_all("http://datamall2.mytransport.sg/ltaodataservice/BusStops%22")
    with open("stops.json", "w") as f:
        f.write(json.dumps(stops))

    #Datapoints stored and dumped into .json files as stops.json
    Busservices = fetch_all("http://datamall2.mytransport.sg/ltaodataservice/BusServices%22")

    with open("services.json", "w") as f:
        f.write(json.dumps(services))
    #Datapoints stored and dumped into .json files as stops.json
    Busroutes = fetch_all("http://datamall2.mytransport.sg/ltaodataservice/BusRoutes%22)
    with open("routes.json", "w") as f:
        f.write(json.dumps(routes))